<a href="https://colab.research.google.com/github/azizdafi/Practice-and-revision-material/blob/main/Revision_and_concepts_for_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Variables
A variable is created the moment you first assign a value to it.

### Rules for declaring a variable:

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)
* A variable name cannot be any of the Python keywords.

Note: Remember that variable names are case-sensitive

Some example of declaring a variable.

In [ ]:
x = 5       # this creates a variable of type int
print(x)
print(type(x))
###########################
y = "John"       # this creates a variable of type str
print(y)
print(type(y))
###########################
z = 1.0       # this creates a variable of type float
print(z)
print(type(z))
###########################
z = 1 + 4j       # this creates a variable of type Complex
print(z)
print(type(z))
x = True       # this creates a variable of type Boolean
print(x)
print(type(x))
###########################

5
<class 'int'>
John
<class 'str'>
1.0
<class 'float'>
(1+4j)
<class 'complex'>
True
<class 'bool'>


## Python Casting

forcing a data type to change its type is known as casting, how ever it is important for us to undersatnd that the forcefull casting can be done only if the data can be converted to what we are planning to, for example we cannot convert string a as int.


In [ ]:
var =
x = int(1)   # x will be int
x = float(1)     # x will be float (1.0)
x = str(3.0)  # z will be string  ('3.0')

## Strings

In [ ]:
print("Hello with double quotes")
print('Hello with single quotes')
a = "Hello assigned as variable"
print(a)
a = """Hello with multiline
string assigned"""
print(a)

Hello with double quotes
Hello with single quotes
Hello assigned as variable
Hello with multiline
string assigned


In [ ]:
# String slicing:
b = "Hello, World!"
print(b[2:5])
# indexing starts from 0 till n-1 so here output is "llo"
# note: charecter present in location 5 is not printed

llo


In [ ]:
# Get the characters from the start to position 5 (not included)
b = "Hello, World!"
print(b[:5])
print(b[5:-1]) #prints from 5 till last but 1

Hello
, World


## String Methods and examples

####Methods


In [ ]:
txt = "hello, and welcome to my world."
x = txt.capitalize()
print (x)

Hello, and welcome to my world.


###similar methods

**capitalize()**   
Converts the first character to upper case  
*Example Usage:*  
x = txt.capitalize()

---
**casefold()**
Converts string into lower case  
x = txt.casefold()

---
**center()**
Returns a centered string  
*Example Usage:*  
x = txt.center(20)

---
**count()**
Returns the number of times a specified value occurs in a string  
*Example Usage:*  
x = txt.count("apple")

---
**encode()**
Returns an encoded version of the string  
*Example Usage:*  
x = txt.encode()

---
**endswith()**
Returns true if the string ends with the specified value  
*Example Usage:*  
x = txt.endswith(".")

---
**expandtabs()**
Sets the tab size of the string  
*Example Usage:*  
x =  txt.expandtabs(2)

---
**find()**
Searches the string for a specified value and returns the position of where it was found  
*Example Usage:*  
x = txt.find("welcome")

---
**format()**
Formats specified values in a string  
*Example Usage:*  
print(txt.format(price = 49))

---
**format_map()**
Formats specified values in a string  
*Example Usage:*  


---
**index()**
Searches the string for a specified value and returns the position of where it was found  
*Example Usage:*  
x = txt.index("welcome")

---
**isalnum()**
Returns True if all characters in the string are alphanumeric  
*Example Usage:*  
x = txt.isalnum()

---
**isalpha()**
Returns True if all characters in the string are in the alphabet  
*Example Usage:*  
x = txt.isalpha()

---
**isascii()**
Returns True if all characters in the string are ascii characters  
*Example Usage:*  
x = txt.isascii()

---
**isdecimal()**
Returns True if all characters in the string are decimals  
*Example Usage:*  
x = txt.isdecimal()

---
**isdigit()**
Returns True if all characters in the string are digits  
*Example Usage:*  
x = txt.isdigit()

---
**isidentifier()**
Returns True if the string is an identifier  
*Example Usage:*  
x = txt.isidentifier()


---
**islower()**
Returns True if all characters in the string are lower case  
*Example Usage:*  
x = txt.islower()

---
**isnumeric()**
Returns True if all characters in the string are numeric  
*Example Usage:*  
x = txt.isnumeric()

---
**isprintable()**
Returns True if all characters in the string are printable  
*Example Usage:*  
x = txt.isprintable()

---
**isspace()**
Returns True if all characters in the string are whitespaces  
*Example Usage:*  
x = txt.isspace()

---
**istitle()**
Returns True if the string follows the rules of a title  
*Example Usage:*  
x = txt.istitle()

---
**isupper()**
Returns True if all characters in the string are upper case  
*Example Usage:*  
x = txt.isupper()

---
**join()**
Joins the elements of an iterable to the end of the string  
*Example Usage:*  
x = "#".join(myTuple/list)

---
**ljust()**
Returns a left justified version of the string  
*Example Usage:*  
x = txt.ljust(20)

---
**lower()**
Converts a string into lower case  
*Example Usage:*  
x = txt.lower()

---
**lstrip()**
Returns a left trim version of the string  
*Example Usage:*  
x = txt.lstrip()

---
**maketrans()**
Returns a translation table to be used in translations  
*Example Usage:*  
mytable = str.maketrans("S", "P")

---
**partition()**
Returns a tuple where the string is parted into three parts  
*Example Usage:*  
x = txt.partition("bananas")

---
**replace()**
Returns a string where a specified value is replaced with a specified value  
*Example Usage:*  
x = txt.replace("bananas", "apples")

---
**rfind()**
Searches the string for a specified value and returns the last position of where it was found  
*Example Usage:*  
x = txt.rfind("casa")

---
**rindex()**
Searches the string for a specified value and returns the last position of where it was found  
*Example Usage:*  
x = txt.rindex("casa")

---
**rjust()**
Returns a right justified version of the string  
*Example Usage:*  
x = txt.rjust(20)

---
**rpartition()**
Returns a tuple where the string is parted into three parts  
*Example Usage:*  
x = txt.rpartition("bananas")

---
**rsplit()**
Splits the string at the specified separator, and returns a list  
*Example Usage:*  
x = txt.rsplit(", ")

---
**rstrip()**
Returns a right trim version of the string  
*Example Usage:*  
x = txt.rstrip()

---
**split()**
Splits the string at the specified separator, and returns a list  
*Example Usage:*  
x = txt.split()

---
**splitlines()**
Splits the string at line breaks and returns a list  
*Example Usage:*  
x = txt.splitlines()

---
**startswith()**
Returns true if the string starts with the specified value  
*Example Usage:*  
x = txt.startswith("Hello")

---
**strip()**
Returns a trimmed version of the string  
*Example Usage:*  
x = txt.strip()

---
**swapcase()**
Swaps cases, lower case becomes upper case and vice versa  
*Example Usage:*  
x = txt.swapcase()

---
**title()**
Converts the first character of each word to upper case  
*Example Usage:*  
x = txt.title()

---
**translate()**
Returns a translated string  
*Example Usage:*  
use a dictionary with ascii codes to replace 83 (S) with 80 (P):  
mydict = {83:  80}  
txt = "Hello Sam!"  
print(txt.translate(mydict))  
output: Hello Pam!

---
**upper()**
Converts a string into upper case  
*Example Usage:*  
x = txt.upper()

---
**zfill()**
Fills the string with a specified number of 0 values at the beginning  
*Example Usage:*  
x = txt.zfill(10)

---

####List

Lists are used to store multiple items in a single variable.

Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are  
Tuple   
Set  
Dictionary

In [ ]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist)
print(len(thislist))
print(type(thislist))
print(thislist[0]) # indexing starts from 0
print(thislist[-1]) #prints last item in the list
print(thislist[2:5]) #prints 3rd item till 5th(excluding the item indexed at 5)
print(thislist[:4]) #Prints first 4
print(thislist[2:]) #prints all after 3

#if condition checking
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")
thislist[1] = "blackcurrant" #replaces banana to blackcurrant
print(thislist)

thislist.append("litchy") #adds litchy at the last
print(thislist)

thislist.remove("melon") #removes melon from list
print(thislist)
thislist.sort(reverse = False) #sorts list items
print(thislist)
del thislist #delete the list
# print(thislist)

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
7
<class 'list'>
apple
mango
['cherry', 'orange', 'kiwi']
['apple', 'banana', 'cherry', 'orange']
['cherry', 'orange', 'kiwi', 'melon', 'mango']
Yes, 'apple' is in the fruits list
['apple', 'blackcurrant', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
['apple', 'blackcurrant', 'cherry', 'orange', 'kiwi', 'melon', 'mango', 'litchy']
['apple', 'blackcurrant', 'cherry', 'orange', 'kiwi', 'mango', 'litchy']
['apple', 'blackcurrant', 'cherry', 'kiwi', 'litchy', 'mango', 'orange']


The list is changeable, allows Duplicates.  
we can get length of list by len function  
List items are indexed and you can access them by referring to the index number

####Tuples

Tuples are used to store multiple items in a single variable.  
A tuple is a collection which is ordered and unchangeable.
Tuple items are ordered, unchangeable, and allow duplicate values.

In [ ]:
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)
print(len(thistuple))
print(type(thistuple))
# thistuple = ("apple",) #for single item tuple remember the comma
# accessing tuple is same as list

#umpacking tuple:
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

# Looping is same like list

#tuple method
thistuple = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)
x = thistuple.count(5)
print(x)

('apple', 'banana', 'cherry', 'apple', 'cherry')
5
<class 'tuple'>
apple
banana
cherry
2


####Set

Sets are used to store multiple items in a single variable.  
A set is a collection which is unordered, unchangeable*, and unindexed.  
Set items are unordered, unchangeable, and do not allow duplicate values.

In [ ]:
thisset = {"apple", "banana", "cherry", True, 1, 2}
print(thisset)

# access list itmes is same as list

# adding item to set
thisset1 = {"apple", "banana", "cherry"}
thisset1.add("orange")
print(thisset1)
# removing item
thisset1 = {"apple", "banana", "cherry"}
thisset1.remove("banana")
print(thisset1)
print()
# Looping is same as list

# joining 2 sets
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}
set3 = set1.union(set2)
print(set3)

{True, 'apple', 2, 'banana', 'cherry'}
{'apple', 'banana', 'orange', 'cherry'}
{'apple', 'cherry'}

{'a', 1, 2, 3, 'c', 'b'}


####Dictionary

Dictionaries are used to store data values in key:value pairs.  
A dictionary is a collection which is ordered*, changeable and do not allow duplicates  
Dictionaries are written with curly brackets, and have keys and values:

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
print()
# access by key
print(thisdict["brand"])

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
# adding new key value pair to dict
thisdict["color"] = "red"
print(thisdict)

if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary")

# updating value in dict
thisdict["year"] = 2018
print(thisdict)

# removing key value pair in dict
thisdict.pop("color")
print(thisdict)


# looping in dictionary
for key, value in thisdict.items():
  print(key, value)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

Ford
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
Yes, 'model' is one of the keys in the thisdict dictionary
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}
brand Ford
model Mustang
year 2018


In [ ]:
# dictionary of dictionar access
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily)
for k, v in myfamily.items():
	for k1, v1 in v.items():
		print(k1, v1)

{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}
name Emil
year 2004
name Tobias
year 2007
name Linus
year 2011


####If ... Else

In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a is greater than b


In [ ]:
print(a) if a > b else print(b)

200


In [ ]:
a = 330
b = 330
print(a) if a > b else print("equal") if a == b else print(b)

equal


In [ ]:
# Nested if
x = 41

if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

Above ten,
and also above 20!


####While Loops

In [ ]:
# With the while loop we can execute a set of statements as long as a condition is true.
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


####For Loops

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [ ]:
# for itterating in string
for x in "banana":
  print(x)

b
a
n
a
n
a


####Python Functions

A function is a block of code which only runs when it is called.  
You can pass data, known as parameters, into a function.  
A function can return data as a result.  
In Python a function is defined using the def keyword:

In [1]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


In [ ]:
# passing argivment
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Refsnes")

Emil Refsnes


In [ ]:
# setting default value in function
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


Python also accepts function recursion, which means a defined function can call itself.

Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.

The developer should be very careful with recursion as it can be quite easy to slip into writing a function which never terminates, or one that uses excess amounts of memory or processor power. However, when written correctly recursion can be a very efficient and mathematically-elegant approach to programming.

In this example, tri_recursion() is a function that we have defined to call itself ("recurse"). We use the k variable as the data, which decrements (-1) every time we recurse. The recursion ends when the condition is not greater than 0 (i.e. when it is 0).

To a new developer it can take some time to work out how exactly this works, best way to find out is by testing and modifying it.

In [ ]:
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)



Recursion Example Results
1
3
6
10
15
21


21

####Lambda

A lambda function is a small anonymous function.  
A lambda function can take any number of arguments, but can only have one expression.  

The power of lambda is better shown when you use them as an anonymous function inside another function.  
Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

In [ ]:
x = lambda a, b, c: a + b + c
print(x(5, 6, 2))

13


In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(3)

print(mydoubler(11))

33


####Class

Almost everything in Python is an object, with its properties and methods.  
A Class is like an object constructor, or a "blueprint" for creating objects.

In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

# we can modify parameters like this:
p1.age = 40
print(p1.age)

John
36
40


The \_\_str__() function controls what should be returned when the class object is represented as a string.

If the \_\_str__() function is not set, the string representation of the object is returned:

In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"{self.name}({self.age})"

p1 = Person("John", 36)

print(p1)

John(36)


Objects can also contain methods. Methods in objects are functions that belong to the object.

Let us create a method in the Person class:

In [ ]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()


Hello my name is John


####NumPy

NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.  
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.  
NumPy stands for Numerical Python.

####**Why Use NumPy?**
In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.  
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with **ndarray** very easy.

####**Which Language is NumPy written in?**
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

NumPy is usually imported under the np alias.

In [ ]:
import numpy as np

print(np.__version__)

1.22.4


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(f'the array {arr}')
print(type(arr))

print('dimentions of ndarray')
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print('setting dimentions to list of numbers manually')
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print('\n In this array the innermost dimension (5th dim) has 4 elements, \n the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, \n the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.')

the array [1 2 3 4 5]
<class 'numpy.ndarray'>
dimentions of ndarray
0
1
2
3
setting dimentions to list of numbers manually
[[[[[1 2 3 4]]]]]
number of dimensions : 5

 In this array the innermost dimension (5th dim) has 4 elements, 
 the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, 
 the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.


#####Indexing in NumPy

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

2nd element on 1st row:  2
6


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6



Same like lists using the above logic we can do negative indexing.

#####Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
# Array shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print('shape of array :', newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
shape of array : (2, 3, 2)


In [ ]:
# Itterating in numpy array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

# Alternate method
print('\n\nAlternate Method')
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8
9
10
11
12


Alternate Method
1
2
3
4
5
6
7
8


In [ ]:
# Joining NumPy Arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print('axis as 1')
print(arr)
arr = np.concatenate((arr1, arr2), axis=0)
print('axis as 0')
print(arr)

axis as 1
[[1 2 5 6]
 [3 4 7 8]]
axis as 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# NumPy provides a helper function: hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print('horizontal stacking')
print(arr)
arr = np.vstack((arr1, arr2))
print('vertical stacking')
print(arr)

horizontal stacking
[1 2 3 4 5 6]
vertical stacking
[[1 2 3]
 [4 5 6]]


In [ ]:
# array splitting
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
# getting index of the element (where)
arr = np.array([1, 2, 3, 4, 5, 4, 4,3,3])
x = np.where(arr == 4)
print(x)
print('x == 3')
x = np.where(arr == 3)
print(x)

(array([3, 5, 6]),)
x == 3
(array([2, 7, 8]),)


In [ ]:
# Sorting NP array
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr, 'it just sorts temp as its a method not function')

[0 1 2 3]
[3 2 0 1] it just sorts temp as its a method not function


In [ ]:
# filtering array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


#####Random Number

In [ ]:
from numpy import random
x = random.randint(100)   # random int value within 100
print(x)
x = random.rand()         #rendom float value
print(x)

x=random.randint(100, size=(5))   #list of 5 numbers

print(x)

91
0.5285352708935245
[30 73 34  2 91]


In [ ]:
# Random choice with probability
# Note: The sum of all probability numbers should be 1.
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 5 5 7 7 5 3 7 5 3 7 5 7 3 7 5 7 7 5 5 7 7 5 7 7 7 5 7 7 7 7 7 5 7 7 5
 5 5 5 7 7 5 7 3 7 7 7 7 7 5 7 7 7 3 7 5 7 7 7 7 7 3 7 7 5 7 3 7 7 7 7 7 5
 7 7 5 3 5 5 7 5 5 7 7 5 5 7 5 7 7 7 7 7 7 7 5 5 7 7]


####Pandas

What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

What Can Pandas Do?
Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?
What is average value?  
Max value?  
Min value?  
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.  

In [ ]:
# Example for series
import pandas as pd
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64


if we have data as list or a dictionary with one key and and one value pair we use Series note the capital S

In [ ]:
# dataframe
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)
print('\n\nindexing by location')
# indexing by location
print(df.loc["day2"])

      calories  duration
day1       420        50
day2       380        40
day3       390        45


indexing by location
calories    380
duration     40
Name: day2, dtype: int64


# how we read csv
df = pd.read_csv('filepath.csv')

print(df)

# similarly json
df = pd.read_json('data.json')

print(df.to_string())

In [ ]:
data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [ ]:
file_path = '/content/drive/MyDrive/Colab Notebooks/data/dat/data.csv'
df = pd.read_csv(file_path)
print(df.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [ ]:
df1 = df.copy()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
df.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
df.shape

(169, 4)

In [ ]:
dup = df.duplicated().sum()
print(dup, '\n', '*'*30)
missing_values = df.isna().sum()
print(missing_values)

7 
 ******************************
Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64


In [ ]:
# # to drop na
# df = df.dropna()
# # to drop subset of null column
# df = df.drop_duplicates(subset=['App'],keep="first")

for numpy and pandas revision  
[practice problems](https://colab.research.google.com/drive/1rgRdE1j3E_MCH1xyIUSZBmb8tZszSgJl?usp=sharing)